language: go

go:
  - tip

branches:
  only:
  - master
  - develop

notifications:
  email: false

before_install:
  - go get github.com/yuin/gopher-lua
  - go get github.com/alecthomas/chroma/quick
  - go get github.com/fatih/color
  - go get github.com/onsi/ginkgo/ginkgo
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/lawrencewoodman/roveralls

script:
- $HOME/gopath/bin/ginkgo -cover -r -v
- $HOME/gopath/bin/roveralls
- $HOME/gopath/bin/goveralls -coverprofile=roveralls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN